So much for so little...

diff --git a/buildlib b/buildlib
--- a/buildlib
+++ b/buildlib
@@ -1,1 +1,242 @@
-#!/bin/bash
+#!/bin/bash -
+#-----------------------------------------------------#
+# buildlib
+#
+# Builds a library to ship with a shell script
+#-----------------------------------------------------#
+#-----------------------------------------------------#
+# Licensing
+# ---------
+# 
+# Copyright (c) 2013 Vokayent
+# 
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+# 
+# The above copyright notice and this permission notice shall be included in
+# all copies or substantial portions of the Software.
+# 
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+# THE SOFTWARE.
+#-----------------------------------------------------#
+PROGRAM="buildlib"
+
+
+#-----------------------------------------------------#
+#
+# Strings
+#-----------------------------------------------------#
+# break_list_by_delim() 
+# creates an array based on some set of delimiters.
+break_list_by_delim() {
+	mylist=(`printf $1 | sed "s/${DELIM}/ /g"`)
+	echo ${mylist[@]}		# Return the list all ghetto-style.
+} # break_list_by_delim()
+
+
+# break_maps_by_delim() 
+# gives a map based on a set of delimiters.
+break_maps_by_delim() {
+	join="${2-=}"			# Allow for an alternate map marker.
+	local m=(`printf $1 | sed "s/${join}/ /g"`)
+	echo ${m[@]}			# Return the list all ghetto-style.
+} # break_maps_by_delim()  
+
+
+#-----------------------------------------------------#
+#
+# Arrays 
+#-----------------------------------------------------#
+# is_element_present_in() 
+# Check if $2 is found within array $1
+is_element_present_in() {
+	# Catch arguments.
+	if [ -z "$1" ] || [ -z "$2" ]
+	then
+		echo "Improper arguments supplied to is_element_present_in()"
+		echo "You've made an error in coding!"
+		exit 1
+	fi
+
+	# Catch arguments.
+	ARR="$(eval 'echo ${'$1'[@]}')"
+	VS_ELE="$2"
+	STAT=
+
+	# Compare each element.
+	for ELE in ${ARR[@]}
+	do
+		[ $ELE == $VS_ELE ] && STAT="true" && break 
+	done
+
+	# Return a status.
+	[ -z $STAT ] && STAT="false"
+	echo $STAT
+} # is_element_present_in() 
+
+
+# usage() - Show usage message and die with $STATUS
+usage() {
+   STATUS="${1:-0}"
+   echo "Usage: ./${PROGRAM}
+	[ -  ]
+
+-m | --manifest               desc
+-l | --list                   desc
+-w | --with <arg>             desc
+-d | --depcheck <arg>         desc
+-n | --name <arg>             desc
+-s | --standard_dirs <arg>    desc
+-d | --db                     desc
+-i | --initial-run            desc
+-s | --security               desc
+-i | --install                desc
+-u | --uninstall              desc
+-v|--verbose                  Be verbose in output.
+-h|--help                     Show this help and quit.
+"
+   exit $STATUS
+}
+
+
+# Die if no arguments received.
+[ -z $BASH_ARGV ] && printf "Nothing to do\n" && usage 1
+
+# Process options.
+while [ $# -gt 0 ]
+do
+   case "$1" in
+     -m|--manifest)
+         DO_MANIFEST=true
+      ;;
+     -l|--list)
+         DO_LIST=true
+      ;;
+     -w|--with)
+         DO_WITH=true
+         shift
+         WITH="$1"
+      ;;
+     -d|--depcheck)
+         DO_DEPCHECK=true
+         shift
+         DEPCHECK="$1"
+      ;;
+     -n|--name)
+         DO_NAME=true
+         shift
+         NAME="$1"
+      ;;
+     -s|--standard_dirs)
+         DO_STANDARD_DIRS=true
+         shift
+         STANDARD_DIRS="$1"
+      ;;
+     -d|--db)
+         DO_DB=true
+      ;;
+     -i|--initial-run)
+         DO_INITIAL_RUN=true
+      ;;
+     -s|--security)
+         DO_SECURITY=true
+      ;;
+     -i|--install)
+         DO_INSTALL=true
+      ;;
+     -u|--uninstall)
+         DO_UNINSTALL=true
+      ;;
+      -v|--verbose)
+        VERBOSE=true
+      ;;
+      -h|--help)
+        usage 0
+      ;;
+      -*)
+      printf "Bad argument.\n";
+      exit 1
+     ;;
+      *) break;;
+   esac
+shift
+done
+
+# manifest
+if [ ! -z $DO_MANIFEST ]
+then
+   echo '...'
+fi
+
+# list
+if [ ! -z $DO_LIST ]
+then
+	# Find each function name ( # [a-z]() )
+	# Get the name, range of description, and range of function.
+	# Save all of these to array.
+	# Should work on both DO_WITH and DO_LIST
+   echo '...'
+fi
+
+# with
+if [ ! -z $DO_WITH ]
+then
+   echo '...'
+fi
+
+# depcheck
+if [ ! -z $DO_DEPCHECK ]
+then
+   echo '...'
+fi
+
+# name
+if [ ! -z $DO_NAME ]
+then
+   echo '...'
+fi
+
+# standard_dirs
+if [ ! -z $DO_STANDARD_DIRS ]
+then
+   echo '...'
+fi
+
+# db
+if [ ! -z $DO_DB ]
+then
+   echo '...'
+fi
+
+# initial_run
+if [ ! -z $DO_INITIAL_RUN ]
+then
+   echo '...'
+fi
+
+# security
+if [ ! -z $DO_SECURITY ]
+then
+   echo '...'
+fi
+
+# install
+if [ ! -z $DO_INSTALL ]
+then
+   echo '...'
+fi
+
+# uninstall
+if [ ! -z $DO_UNINSTALL ]
+then
+   echo '...'
+fi
diff --git a/buildopts b/buildopts
--- a/buildopts
+++ b/buildopts
@@ -2,14 +2,7 @@
 #-----------------------------------------------------#
 # buildopts.sh
 #
-# Will create a list based on input.
-#
-# --------------
-# Documentation.
-# --------------
-# 
-# Quick option for building out the options within
-# a shell script.
+# Builds out the innards of a shell script.
 #
 # ---------
 # Licensing
@@ -45,23 +38,30 @@ usage() {
 ./$PROGRAM [ - ]
 
 General options:
--f | --from <list>      Supply a list of options to create flags for.
--g | --generate         Generate a new manifest file.
--c | --clobber          Overwrite file if one exists.
+-f | --from <list>          Supply a list of options to create flags for.
+-g | --generate             Generate a new manifest file.
+-c | --clobber              Overwrite file if one exists.
 
 Shell Script tuning:
--a | --according-to     Bla...
--d | --die-on-no-arg    Make changes on <file>.
--e | --license <type>   Add a particular license at the top of the script.
--l | --logic            Generate accompanying logic.
--n | --name <name>      Set up a script name.
--o | --options          Generate a list of options.
--t | --to <file>        Make changes on <file>.
--u | --usage <file>     Make changes on <file>.
+-d | --die-on-no-arg        Make changes on <file>.
+-s | --summary <summ>       Add a quick summary.
+-e | --license <type>       Add a particular license at the top of the script.
+-l | --logic                Generate accompanying logic.
+-n | --name <name>          Set up a script name.
+-p | --program <name>       Set up a script name and use this name in a \$PROGRAM variable.
+-o | --options              Generate a list of options.
+-x | --only-options <list>  Do not generate logic for items in list.
+-t | --to <file>            Make changes on <file>.
+-u | --usage <file>         Make changes on <file>.
+-z | --shell <type>         Choose a particular shell for she-bang line.
+                            (Default is bash)
+-m | --from-manifest        Generate through the use of a manifest file.
+-b | --binref               Include references to script file and directory 
+                            that script resides in.
 
 General Options:
--v | --verbose          Be verbose in output.
--h | --help             Show help and quit.
+-v | --verbose              Be verbose in output.
+-h | --help                 Show help and quit.
 "
 	exit $STATUS
 }
@@ -79,22 +79,134 @@ break_maps_by_delim() {
 	echo ${m[@]}			# Return the list all ghetto-style.
 }
 
+# is_element_present_in() - Check if $2 is found within array $1
+is_element_present_in() {
+	# Catch arguments.
+	if [ -z "$1" ] || [ -z "$2" ]
+	then
+		echo "Improper arguments supplied to is_element_present_in()"
+		echo "You've made an error in coding!"
+		exit 1
+	fi
+
+	# Catch arguments.
+	ARR="$(eval 'echo ${'$1'[@]}')"
+	VS_ELE="$2"
+	STAT=
+
+	# Compare each element.
+	for ELE in ${ARR[@]}
+	do
+		[ $ELE == $VS_ELE ] && STAT="true" && break 
+	done
+
+	# Return a status.
+	[ -z $STAT ] && STAT="false"
+	echo $STAT
+}
+
+
+# push_option_alpha() - Chooses distinct letters for options.
+# If an option letter is taken, use something else within the string first.
+# SLOW AS HELL!!!
+declare -a OPTION_ALPHA 
+push_option_alpha() {
+	# Create array.
+	if [ ${#OPTION_ALPHA[@]} -eq 0 ]
+	then 
+		#echo Not filled: ${#OPTION_ALPHA[@]}
+		OPTION_ALPHA[0]="h"
+		OPTION_ALPHA[1]="v"
+	fi
+
+	#echo Modified: ${#OPTION_ALPHA[@]}
+	#echo $(is_element_present_in "OPTION_ALPHA" $1)
+
+	# Push to it.
+	if [ ! -z "$1" ] 
+	then
+		# ...
+		if [ $(is_element_present_in "OPTION_ALPHA" $1) == false ]
+		then
+			OPTION_ALPHA[${#OPTION_ALPHA[@]}]="$1"
+
+		# Choose a new letter.
+		else
+			for n in `seq 0 $(( ${#OPT_NAME} - 1 ))`
+			do
+				OPT_ALP_LETTER=${OPT_NAME:${n}:1}
+
+				# Break on hyphens.
+				if [[ $OPT_ALP_LETTER == '-' ]]
+				then
+					continue
+
+				# Keep moving.
+				elif [ $(is_element_present_in "OPTION_ALPHA" $OPT_ALP_LETTER) == false ]
+				then
+					OPTION_ALPHA[${#OPTION_ALPHA[@]}]=${OPT_ALP_LETTER}
+					OPT_ALP_SET=true
+					break
+				fi
+			done
+
+			# Oh no!  What if we still couldn't find a letter?
+			# (We've reached the end of the food chain...)
+			# There is a better  way to do this... ( LETTERS=$( echo [a-z] ) )
+			declare -a OA_LETTERS
+			OA_LETTERS=(a b c d e f g h i j k l m n o p q r s t u v w x y z 1 2 3 4 5 6 7 8 9)	
+			for OAL in ${OA_LETTERS[@]}
+			do
+				if [ $(is_element_present_in "OPTION_ALPHA" $OAL) == false ]
+				then
+					OPTION_ALPHA[${#OPTION_ALPHA[@]}]=${OAL}
+					OPT_ALP_SET=true
+					break
+				fi	
+			done	
+		fi
+	fi
+#	printf ${OPTION_ALPHA[$(( ${#OPTION_ALPHA[@]} - 1 ))]}
+}
+
+
+# get_last_alpha() - Still unsure as to why I need this...
+get_last_alpha () {
+	printf ${OPTION_ALPHA[$(( ${#OPTION_ALPHA[@]} - 1 ))]}
+}
+
+
 # Die if no string received.
-[ -z $BASH_ARGV ] && echo "Nothing to do." && usage 1
+[ -z "$BASH_ARGV" ] && echo "Nothing to do." && usage 1
 while [ $# -gt 0 ]
 do
 	case "$1" in 
+		-b|--bindir)
+			DO_SELFSOURCE=true
+		;;
+
+		-s|--summary)
+			shift
+			SUMMARY="$1"
+		;;
+
 		-f|--from)
 			shift
 			FROM=$1
+		;;
+
+		-p|--program)
+			DO_PROGRAM=true
+			shift
+			NAME="$1"
 		;;
 
 		-g|--generate)
 			GENERATE=true
 		;;
 
-		-c|--clobber)
-			CLOBBER=true
+		-c|--comments)
+			DO_COMMENTS=true
 		;;
 
 		-a|--according-to)
@@ -122,13 +234,22 @@ do
 			FILENAME=$1
 		;;
 
+		-z|--shell)
+			shift
+			SHELL_ARG="$1"
+		;;
 		-n|--name)
 			shift
-			NAME_OF_SCRIPT=$1
+			NAME=$1
 		;;
 
 		-o|--options)
 			DO_OPTIONS=true
+		;;
+
+		-x|--only-options)
+			shift
+			ONLY_OPTIONS="$1"
 		;;
 
 		-t|--to)
@@ -155,25 +276,63 @@ do
 shift
 done
 
-# Need the ability to choose between action flags and logic / arugment flags.
+# No more processing needed.
+if [ -z $DO_LOGIC ] && \
+	[ -z $SELECT_LICENSE ] && \
+	[ -z $DO_OPTIONS ] && \
+	[ -z $SHOW_USAGE ] && \
+	[ -z "$SUMMARY" ] && \
+	[ -z "$NAME" ]
+then
+	echo "Nothing to do!"
+	usage 1
+fi
+
 
 # Generate a file.
 FILENAME=${FILENAME:-'/dev/stdout'}
-if [[ ! $FILENAME == '/dev/stdout' ]] && [ -f $FILENAME ] && [ ! -z $CLOBBER ]
+FILEERR=${FILENAME:-'/dev/stderr'}
+if [[ ! $FILENAME == '/dev/stdout' ]] && [ -f $FILENAME ] 
 then
 	rm $RM_FLAGS $FILENAME
 fi
 
 
 # Choose a shell.
-if [ -z $MODIFY ]
+SHELL=
+case "$SHELL_ARG" in
+	s|sh|SH|sH|Sh)
+		SHELL="sh"
+	;;
+	z|zsh|ZSH|zSH|zSh|Zsh|ZsH)
+		SHELL="zsh"
+	;;
+	b|bash)
+		SHELL="bash"
+	;;
+	c|csh|CSH|cSH|cSh|Csh|CsH)
+		SHELL="csh"
+	;;
+	k|ksh|KSH|kSH|kSh|Ksh|KsH)
+		SHELL="ksh"
+	;;
+	*)
+		SHELL="bash"
+	;;
+esac
+printf "#!/bin/${SHELL} -\n" >> $FILENAME
+
+
+
+# Choose a shell.
+if [ ! -z "$NAME" ] || [ ! -z "$SUMMARY" ]
 then
-	( printf '#!/bin/bash -\n'
+	( printf '#-----------------------------------------------------#\n'
+	printf "# $NAME\n" 
+	printf '#\n'
+	printf "# $SUMMARY\n"
 	printf '#-----------------------------------------------------#\n'
-	printf "# $NAME_OF_SCRIPT\n" 
-	printf '#\n'
-	printf '#\n'
-	printf '#\n' ) >> $FILENAME
+	) >> $FILENAME
 fi
 
 
@@ -182,7 +341,7 @@ if [ ! -z $SELECT_LICENSE ]
 then
 	case $LICENSE in
 		mit)
-LICENSE_BODY='# ---------
+LICENSE_BODY='#-----------------------------------------------------#
 # Licensing
 # ---------
 # 
@@ -219,17 +378,62 @@ LICENSE_BODY="
 fi
 
 
+# Include a reference to self and the program's directory.
+if [ ! -z $DO_SELFSOURCE ] 
+then
+	[ ! -z $DO_COMMENTS ] && printf '\n# References to $SELF\n' >> $FILENAME
+	( printf 'BINDIR="$(dirname "$(readlink -f $0)")"\n'
+	printf 'SELF="$(readlink -f $0)"\n' ) >> $FILENAME
+fi
+
+
+# Use $PROGRAM variable.
+[ ! -z $DO_PROGRAM ] && printf "PROGRAM=\"${NAME}\"\n" >> $FILENAME
+
+
+# Need the ability to choose between action flags and logic / arugment flags.
+# If there's no list, manifest or file to read, this is pretty much useless.
+if [ -z "$FROM" ] || [[ "${FROM:0:1}" == '-' ]]
+then 
+	if [ ! -z $SHOW_USAGE ] || \
+		[ ! -z $DO_OPTIONS ] || \
+		[ ! -z $DO_LOGIC ] || \
+		[ ! -z $ONLY_OPTIONS ]
+	then
+	echo "No list supplied via --from!" >> $FILEERR
+	usage 1
+	else
+		exit 0
+	fi
+fi
+
+
 # Catch arguments here if we want them.
 OPTS_FROM_LIST=( $( break_list_by_delim $FROM ) )
+[ ! -z "$ONLY_OPTIONS" ] && NO_OPT_FROM_LIST=( $( break_list_by_delim $ONLY_OPTIONS ) )
 COUNTER=0
 declare -a ARG_SUB_SET
+declare -a GENERATE_LOGIC_SET
 for EACH_ARG in ${OPTS_FROM_LIST[@]}
 do
+	# ...
 	if [[ ${EACH_ARG:0:1} == '@' ]] 
 	then 
  		ARG_SUB_SET[$COUNTER]=true 
 	else
  		ARG_SUB_SET[$COUNTER]=false
+	fi
+
+	# Set no logic.
+	if [ ! -z "$NO_OPT_FROM_LIST" ]
+	then
+		if [ $( is_element_present_in "NO_OPT_FROM_LIST" $EACH_ARG ) == true ] || \
+			[ $( is_element_present_in "NO_OPT_FROM_LIST" ${EACH_ARG:1:${#EACH_ARG}} ) == true ]
+		then
+ 			GENERATE_LOGIC_SET[$COUNTER]=true 
+		else
+ 			GENERATE_LOGIC_SET[$COUNTER]=false
+		fi
 	fi
 
 	COUNTER=$(( $COUNTER + 1 ))
@@ -246,10 +450,11 @@ LIM=$(( ${#OPTS_FROM_LIST[@]} - 1 ))
 # Show a usage message.
 if [ ! -z $SHOW_USAGE ]
 then
+	# Print any comments. 
+	[ ! -z $DO_COMMENTS ] && printf '\n# usage() - Show usage message and die with $STATUS\n' >> $FILENAME
+
 	# Eventually add option for top tags.
-	( printf '\n# usage message\n'
-	printf '# Show a usage message and die.\n'
-	printf 'usage() {\n'
+	( printf 'usage() {\n'
 	printf '   STATUS="${1:-0}"\n'
 	printf '   echo "Usage: ./${PROGRAM}\n\t[ -  ]\n\n' ) >> $FILENAME
 
@@ -261,15 +466,26 @@ then
 		then
 			ARG_FLAG_NAME="${ARG_FLAG_SET[$OPTCOUNT]:1:${#ARG_FLAG_SET[$OPTCOUNT]}}"
 			OPT_NAME="$( echo ${ARG_FLAG_NAME} | tr [A-Z] [a-z] )"
+		#	ARG_LETTER=`push_option_alpha ${OPT_NAME:0:1}`
+		#	push_option_alpha ${OPT_NAME:0:1}
+		#	ARG_LETTER="$(get_last_alpha)"
+			ARG_LETTER="${OPT_NAME:0:1}"
+
 			printf -- \
-				"$(printf -- "-${OPT_NAME:0:1} | --${OPT_NAME} <arg>                     " | \
+				"$(printf -- "-${ARG_LETTER} | --${OPT_NAME} <arg>                     " | \
 				head -c 30)" >> $FILENAME
 			printf "desc\n" >> $FILENAME
 
 		# Print formatted help without arguments.
 		else
+			OPT_NAME="$( echo ${OPTS_FROM_LIST[$OPTCOUNT]} | tr [A-Z] [a-z] )"
+#			ARG_LETTER=$(push_option_alpha ${OPT_NAME:0:1})
+	#		push_option_alpha ${OPT_NAME:0:1}
+	#		ARG_LETTER="$(get_last_alpha)"
+			ARG_LETTER="${OPT_NAME:0:1}"
+
 			printf -- \
-				"$(printf -- "-${OPTS_FROM_LIST[$OPTCOUNT]:0:1} | --${OPTS_FROM_LIST[$OPTCOUNT]}                      " | \
+				"$(printf -- "-${ARG_LETTER} | --${OPTS_FROM_LIST[$OPTCOUNT]}                      " | \
 				head -c 30)" >> $FILENAME
 			printf "desc\n" >> $FILENAME
 		fi
@@ -287,23 +503,24 @@ fi
 # Die on no arguments.
 if [ ! -z $DO_DIENARG ]
 then
+	# Print any comments. 
+	[ ! -z $DO_COMMENTS ] && printf '\n# Die if no arguments received.' >> $FILENAME
+
+	# Die!
 	printf '\n[ -z $BASH_ARGV ] && printf "Nothing to do\\n" && usage 1\n' >> $FILENAME
 fi
 
 
-# If there's no list, manifest or file to read, this is pretty much useless.
-if [ -z "$FROM" ] || [[ "${FROM:0:1}" == '-' ]]
-then 
-	echo "No list supplied!" 
-	usage 1
-fi
-
 
 # Process all the options.
+unset OPTION_ALPHA
 if [ ! -z $DO_OPTIONS ]
 then
+	# Print any comments. 
+	[ ! -z $DO_COMMENTS ] && printf '\n# Process options.' >> $FILENAME
+
 	# Do some basics.
-	( printf 'while [ $# -gt 0 ]\ndo\n'
+	( printf '\nwhile [ $# -gt 0 ]\ndo\n'
 	printf '   case "$1" in\n' ) >> $FILENAME
 
 
@@ -317,23 +534,35 @@ then
 			ARG_FLAG_NAME="${ARG_FLAG_SET[$OPTCOUNT]:1:${#ARG_FLAG_SET[$OPTCOUNT]}}"
 			OPT_NAME="$( echo ${ARG_FLAG_NAME} | tr [A-Z] [a-z] )"
 
+			# This is ridiculous...
+			#push_option_alpha ${OPT_NAME:0:1}
+			#ARG_LETTER="$(get_last_alpha)"
+			ARG_LETTER=${OPT_NAME:0:1}
+
 			# Can optionally loop these to go through whole range.
 			# Also need to check if this first letter is a member of an array.
-			( printf -- "     -${OPT_NAME:0:1}|"
+			#( printf -- "     -${OPT_NAME:0:1}|"
+			( printf -- "     -${ARG_LETTER}|"
 			printf -- "--${OPT_NAME})\n"
 
 			# Wants arg or not?
-			printf "         $ARG_FLAG_NAME=true\n"
+			printf "         DO_$ARG_FLAG_NAME=true\n"
 			printf "         shift\n"
-			printf "         ${ARG_FLAG_NAME}_ARG=\$1\n" ) >> $FILENAME
+			printf "         ${ARG_FLAG_NAME}=\"\$1\"\n" ) >> $FILENAME
 
 			# Unset for the next round.
 			unset ARG_FLAG_NAME
 			unset OPT_NAME
 		else
-			( printf -- "     -${OPTS_FROM_LIST[$OPTCOUNT]:0:1}|"
+			# This is ridiculous...
+			#push_option_alpha ${OPTS_FROM_LIST[$OPTCOUNT]:0:1}
+			#ARG_LETTER="$(get_last_alpha)"
+			ARG_LETTER=${OPTS_FROM_LIST[$OPTCOUNT]:0:1}
+
+			#( printf -- "     -${OPTS_FROM_LIST[$OPTCOUNT]:0:1}|"
+			( printf -- "     -${ARG_LETTER}|"
 			printf -- "--${OPTS_FROM_LIST[$OPTCOUNT]})\n"
-			printf "         ${ARG_FLAG_SET[$OPTCOUNT]}=true\n" ) >> $FILENAME
+			printf "         DO_${ARG_FLAG_SET[$OPTCOUNT]}=true\n" ) >> $FILENAME
 		fi
 
 		printf "      ;;\n" >> $FILENAME
@@ -358,12 +587,23 @@ then
 	for OPTCOUNT in `seq $COUNTER $LIM`
 	do
 		# ...
-		if [[ ${ARG_SUB_SET[$OPTCOUNT]} == true ]]
+		if [[ ${GENERATE_LOGIC_SET[$OPTCOUNT]} == true ]]
+		then
+			continue
+		elif [[ ${ARG_SUB_SET[$OPTCOUNT]} == true ]]
 		then
 			ARG_FLAG_NAME="${ARG_FLAG_SET[$OPTCOUNT]:1:${#ARG_FLAG_SET[$OPTCOUNT]}}"
-			printf "\nif [ ! -z \$${ARG_FLAG_NAME} ]\n" >> $FILENAME
+
+			# Print any comments. 
+			[ ! -z $DO_COMMENTS ] && printf "\n# $(printf ${ARG_FLAG_NAME} | tr '[A-Z]' '[a-z]')" >> $FILENAME
+
+			# Then print the flag.
+			printf "\nif [ ! -z \$DO_${ARG_FLAG_NAME} ]\n" >> $FILENAME
 		else
-			printf "\nif [ ! -z \$${ARG_FLAG_SET[$OPTCOUNT]} ]\n" >> $FILENAME
+			# Print any comments. 
+			[ ! -z $DO_COMMENTS ] && printf "\n# $(printf ${ARG_FLAG_SET[$OPTCOUNT]} | tr '[A-Z]' '[a-z]')" >> $FILENAME
+
+			printf "\nif [ ! -z \$DO_${ARG_FLAG_SET[$OPTCOUNT]} ]\n" >> $FILENAME
 		fi
 
 		( printf "then\n"
