Buildlib now has support for install and uninstall.
Documentation is the next step.

diff --git a/buildlib b/buildlib
--- a/buildlib
+++ b/buildlib
@@ -76,7 +76,10 @@ Library Runtime Actions:
 -s | --standard_dirs <arg>    Convert names in <arg> to variables that 
                               reference your program's common directories.
 -b | --db                     Generate code to create a database. 
--t | --initial-run            Generate code to install a shell script.
+-t | --initial-run            Generate code to run preliminary checks in a 
+                              shell script.
+-y | --initial-install <dir>  Generate code to install a shell script.
+                              ( /usr/bin, /usr/local/bin or $HOME/bin )
 -u | --security               Generate code to secure a shell script.
 -a | --set-all <arg>          Set all flags that do not require an argument.
                               <arg> refers to library name.
@@ -113,70 +116,98 @@ do
 			DO_COMMENTS=true
          DO_DB=true
          DO_INITIAL_RUN=true
+         DO_INITIAL_INSTALL=true
          DO_SECURITY=true
 			shift
 			LIBNAME="$1"
 		;;
+
 	  -c|--comments)
 			DO_COMMENTS=true
 		;;
+
      -w|--with)
          DO_WITH=true
          shift
          WITH="$1"
       ;;
+
      -x|--without)
          shift
          WITHOUT="$1"
       ;;
+
      -z|--all)
          DO_INC_ALL=true
       ;;
+
      -l|--list)
          DO_LIST=true
          shift
          LIST="$1"
       ;;
+
      -n|--name)
          shift
          LIBNAME="$1"
       ;;
+
      -q|--namespace)
          DO_NAMESPACE=true
          shift
          NAMESPACE="$1"
       ;;
+
      --specify-with)
          DO_WITH=true
          DO_SPECIFY_WITH=true
       ;;
+
      -e|--executables)
          DO_EXECUTABLES=true
          shift
          EXECUTABLES="$1"
       ;;
+
      -s|--static)
          DO_STATIC=true
          shift
          STATIC="$1"
       ;;
+
      -d|--depcheck)
          DO_DEPCHECK=true
       ;;
+
      -t|--standard-dirs)
          DO_STANDARD_DIRS=true
          shift
          STANDARD_DIRS="$1"
       ;;
+
      -b|--db)
          DO_DB=true
       ;;
+
+	  -yy|--initial-install)
+			DO_INITIAL_INSTALL=true
+			shift
+			INITIAL_INSTALL_DIR="$1"
+		;; 
+
+	  -y|--initial-install-dir)
+			shift
+			INITIAL_INSTALL_DIR="$1"
+		;;
+
      -i|--initial-run)
          DO_INITIAL_RUN=true
       ;;
+
      -s|--security)
          DO_SECURITY=true
       ;;
+
      -?|--describe)
          DO_DESCRIBE=true
          shift
@@ -267,8 +298,16 @@ then
 fi
 
 
-# depcheck
+# Licenses can still be included as well as banners.
+# ...
 
+
+# Finally, add an individual usage.
+# Easy to lose track of all of this and even how to use everything.
+# For functions that ship with this, just maintain a help file within the code.
+# For functions that do not ship with this (e.g. dependencies from elsewhere or items added 
+# through maintlib, cut their comments.  This can just be a generic option: --help-with <f>
+# ...
 
 
 # executables
@@ -311,6 +350,7 @@ then
 	printf "LIBNAME=\"${LIBNAME}\"\n"
 	printf "PROGRAM_DIR=\"\$HOME/.\${LIBNAME}\"\n" ) >> $FILENAME
 fi
+
 
 # create standard directories 
 if [ ! -z $DO_STANDARD_DIRS ]
@@ -387,6 +427,14 @@ then
 	[ ! -z "$DO_COMMENTS" ] && printf "# Initial deployment.\n" 
 	printf "initial_deploy() {\n" 
 
+	# Verbose eval.
+	printf "\tif [ ! -z \$VERBOSE ] 
+	then
+		ID_MKDIR_FLAGS='-pv'	
+	else
+		ID_MKDIR_FLAGS='-p'	
+	fi\n"
+
 	if [ ! -z "$EXECUTABLES" ]
 	then
 		# Comments 
@@ -398,6 +446,8 @@ then
 		then
 			echo \"\$E is not on system.\"
 			exit 1
+		else
+			[ ! -z \$VERBOSE ] && echo \"$(basename $E) is present at: $E.\"
 		fi
 	done\n"
 	fi
@@ -408,7 +458,7 @@ then
 	printf "
 	for D in \${HOST_DIRS[@]}
 	do
-		mkdir -p \"\$D\"
+		mkdir \$ID_MKDIR_FLAGS \"\$D\"
 	done" 
 	
 	
@@ -420,7 +470,8 @@ then
 		printf "	
 	for SD in \$( ls \$BIN_SQL_DIR )
 	do
-		\$SQLITE \$DB < \$SD
+		[ ! -z \$VERBOSE ] && echo \"Loading tables in: \${BIN_SQL_DIR}/\$SD\"
+		\$SQLITE \$DB < \${BIN_SQL_DIR}/\$SD
 	done"
 	fi
 
@@ -429,23 +480,204 @@ then
 fi
 
 
+# initial_install
+if [ ! -z $DO_INITIAL_INSTALL ]
+then
+	(
+	# Install somewhere.
+	if [ ! -z "$INITIAL_INSTALL_DIR" ]
+	then 
+		if [ ! -z "$DO_COMMENTS" ] 
+		then
+			printf "\n# Install program where?\n" 
+			printf "# ('/usr/bin', '/usr/local/bin', '\$HOME/bin' or another directory entirely.)" 
+		fi
+
+		printf "\nINITIAL_INSTALL_DIR=\"${INITIAL_INSTALL_DIR}\"\n"
+	fi
+	
+	# Start moving through the function.
+	[ ! -z "$DO_COMMENTS" ] && printf "\n# Initial install of program." 
+
+	# Keep track of install directories.
+	printf "\nSW_INSTALL=\"\${PROGRAM_DIR}/INSTALL\""
+
+	# Create the initial_install function
+	printf "\ninitial_install() {\n"
+
+	# Catch args, there are some...
+	printf "# Need some flags to catch install dir, arguments for what should be linked...
+	while [ \$# -gt 0 ]
+	do
+		case "\$1" in
+			--to) 
+				shift
+				INITIAL_INSTALL_DIR="\$1"
+			;;
+			--these) 
+				shift
+				LN_ARGS="\$1"
+			;;
+			-*)
+			break
+			;;
+		esac
+		shift
+	done\n"
+
+	# Be sane about evaluation.
+	# If first arg is '/', then it's a dir.
+	# If first arg is '/', then it's a dir.
+
+	# Verbosity
+	[ ! -z "$DO_COMMENTS" ] && printf "\t# Verbosity flags.\n"
+	printf "\tif [ ! -z \$VERBOSE ] 
+	then
+		SW_LN_FLAGS='-sv'	
+		SW_MKDIR_FLAGS='-pv'	
+		SW_CHMOD_FLAGS='--verbose'	
+	else
+		SW_LN_FLAGS='-s'	
+		SW_MKDIR_FLAGS='-p'	
+		SW_CHMOD_FLAGS='--'	
+	fi\n"
+
+	# This needs to be run a little sooner.
+	# Like at the deploy step.
+	# Though the check still needs to be run here to make sure we can create
+	# an uninstall routine.
+	printf "
+	if [ ! -d \"\$PROGRAM_DIR\" ] 
+	then
+		echo \"Program directory does not exist.\" 
+		echo \"Exiting...\" 
+		exit 1
+	elif [ -d \"\$PROGRAM_DIR\" ] && [ ! -O \"\$PROGRAM_DIR\" ] 
+	then
+		echo \"Program directory is not writeable.  \"
+		echo \"Exiting...\" 
+		exit 1
+	fi\n"
+	
+	# Set an initial install directory if not set yet. 
+	[ ! -z "$DO_COMMENTS" ] && printf "\n\t# Set initial dir if not set.\n"
+	printf "\tINITIAL_INSTALL_DIR=\"\${INITIAL_INSTALL_DIR:-'/usr/local/bin'}\"\n"
+
+
+	# Check if the current user has write access or not.
+	# Uninstall has to work here.
+	[ ! -z "$DO_COMMENTS" ] && printf "\n\t# Die on no permissions if INITIAL_INSTALL_DIR is relative to /."
+
+	printf "
+	if [ -d \"\$INITIAL_INSTALL_DIR\" ] && [ ! -O \"\$INITIAL_INSTALL_DIR\" ] 
+	then
+		echo \"Install directory is not writeable.  Exiting...\" 
+		exit 1
+	fi\n"
+
+
+	# Assume
+	[ ! -z "$DO_COMMENTS" ] && printf "\n\t# Assume this directory could be impractically long."
+
+	printf "
+	if [ ! -d \"\$INITIAL_INSTALL_DIR\" ] 
+	then
+		mkdir \$SW_MKDIR_FLAGS \$INITIAL_INSTALL_DIR 2>/dev/null || SW_MKDIR_FAIL=true
+		if [ ! -z \$SW_MKDIR_FAIL ] 
+		then 
+			echo \"Could not create \$INITIAL_INSTALL_DIR.  Exiting...\" 
+			exit 1
+		fi
+	fi\n"
+
+
+	# Do some more more magic.	
+	[ ! -z "$DO_COMMENTS" ] && printf "\n\t# Check for what type of file exists in \$BINDIR" 
+
+	printf "\n\tSW_INSTALLS=( \$(printf \$1 | sed 's/,/ /g') )
+	declare -a SW_LOCATIONS
+	for FILE in \${SW_INSTALLS[@]}
+	do
+		# If a shell script, did we use an extension? (goal is to have no .sh in /bin)
+		if [ -f \"\${BINDIR}/\${FILE}.sh\" ] 
+		then 
+			FILE=\"\${BINDIR}/\${FILE}.sh\" 
+		elif [ -f \"\${BINDIR}/\${FILE}\" ] 
+		then
+			FILE=\"\${BINDIR}/\${FILE}\" 
+		fi
+
+
+		# Link 
+		LNFILE=\"\$(basename \${FILE})\" 
+
+		# Quick test.
+		if [ -L \"\$LNFILE\" ] 
+		then 
+			echo \"\${PROGRAM} already seems to be installed on this machine.\"
+			echo \"You'll need to uninstall or remove those links first.\"
+			exit
+		fi
+
+
+		# Set x bit, and link.
+		[ ! -x \"\${FILE}\" ] && chmod \$SW_CHMOD_FLAGS 744 \${FILE}
+		ln \$SW_LN_FLAGS \${FILE} \${INITIAL_INSTALL_DIR}/\$LNFILE
+
+
+		# Save the software install location to a file.
+		echo \"\${INITIAL_INSTALL_DIR}/\$LNFILE\" >> \$SW_INSTALL
+	done
+}\n"
+
+
+	# This can be made to go into whatever as long as its parsed.
+	# Load each var to memory and just save the results.
+	[ ! -z "$DO_COMMENTS" ] && printf "\n# For what install would be complete without an uninstall?."
+
+	# Add uninstall() function.
+	printf "\nuninstall() {
+	if [ ! -z \$VERBOSE ] 
+	then
+		UN_RM_FLAGS='-v --'	
+	else
+		UN_RM_FLAGS='--'	
+	fi
+
+	# Stop on problems accessing our install file (like it hasn't been created.)
+	[ ! -f \$SW_INSTALL ] && echo \"Can't access INSTALL file.\" && exit 1
+	while read line
+	do
+		rm \$UN_RM_FLAGS \$line
+	done < \$SW_INSTALL
+
+	# Trash the file.
+	rm \$UN_RM_FLAGS \$SW_INSTALL
+}\n"
+
+	# total_uninstall?
+
+	) >> $FILENAME
+fi
+
+
 # security
 if [ ! -z $DO_SECURITY ]
 then
-	printf '\n' >> $FILENAME
+	( printf '\n' >> $FILENAME
    # Set the right internal field seperator for command line args. 
-	[ ! -z $DO_COMMENTS ] && printf "# Set the right internal field seperator for command line args.\n" >> $FILENAME
-	printf "IFS=' \n\t'\n\n"  >> $FILENAME
+	[ ! -z $DO_COMMENTS ] && printf "# Set the right internal field seperator for command line args.\n" 
+	printf "IFS=' \n\t'\n\n"
 
 	# Limits file creation permissions. 
 	[ ! -z $DO_COMMENTS ] && printf "# Limits file creation permissions.\n" >> $FILENAME
-	( printf "UMASK=002\n" 
-	printf 'umask $UMASK\n\n' ) >> $FILENAME
+	printf "UMASK=002\n" 
+	printf 'umask $UMASK\n\n' 
 
 	# Set a normal path. 
 	[ ! -z $DO_COMMENTS ] && printf "# Set a normal path.\n" >> $FILENAME
-	( printf 'PATH="/usr/local/bin:/bin:/usr/bin"\n' 
-	printf 'export PATH\n' ) >> $FILENAME
+	printf 'PATH="/usr/local/bin:/bin:/usr/bin"\n' 
+	printf 'export PATH\n\n' ) >> $FILENAME
 fi
 
 
